name: Update Contract Reference

on:
  push:
    branch:
      - 'main'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  update-contract:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate current schema
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
          pip install git+https://github.com/MatsMoll/aligned.git@matsei/load-dataset-as-job
          aligned compile

      - name: Archive new aligned schema
        uses: actions/upload-artifact@v3
        with:
          name: contract-latest
          path: contract_store.json
