name: Update Contract Reference

on:
  push:
    branch:
      - 'main'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  update-contract:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: false
          version: 1.5.1

      - name: Generate Contract
      - run: |
          python -m venv .venv --upgrade-deps
          source .venv/bin/activate
          poetry install --no-interaction --no-ansi
          aligned compile

      - name: Archive new aligned schema
        uses: actions/upload-artifact@v3
        with:
          name: contract-latest
          path: contract_store.json
